baseURL: 'http://example.org/'
languageCode: 'en-us'
title: 'XdoctorwhoZ Blog !'
theme: 'PaperMod'


  

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45



minify:
    disableXML: true
    # minifyOutput: true


params:
    
    env: production # to enable google analytics, opengraph, twitter-cards and schema.

    comments: true
    ShowReadingTime: true

    profileMode:
        enabled: true
        title: XdoctorwhoZ Blog !
        imageUrl: avatar.png
        imageTitle: avatar
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - { name: Posts, url: posts }
            - { name: Tags, url: tags }

    cover:
        linkFullImages: true
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page
    
